apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 337683218397.dkr.ecr.ap-south-1.amazonaws.com/reactapp-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/mydb
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: react-app
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
