apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: 337683218397.dkr.ecr.ap-south-1.amazonaws.com/mongo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: react-app
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
